// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package handler

import (
	"net/http"

	group "easy-im/internal/group/internal/handler/group"
	"easy-im/internal/group/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// 创建群组
				Method:  http.MethodPost,
				Path:    "/group/create",
				Handler: group.CreateGroupHandler(serverCtx),
			},
			{
				// 加入群组
				Method:  http.MethodPost,
				Path:    "/group/join",
				Handler: group.JoinGroupHandler(serverCtx),
			},
			{
				// 踢出成员（仅群主/管理员）
				Method:  http.MethodPost,
				Path:    "/group/kick",
				Handler: group.KickMemberHandler(serverCtx),
			},
			{
				// 获取我的群组列表
				Method:  http.MethodGet,
				Path:    "/group/list",
				Handler: group.GetMyGroupsHandler(serverCtx),
			},
			{
				// 获取群成员列表
				Method:  http.MethodGet,
				Path:    "/group/members/:groupId",
				Handler: group.GetGroupMembersHandler(serverCtx),
			},
			{
				// 退出群组
				Method:  http.MethodPost,
				Path:    "/group/quit",
				Handler: group.QuitGroupHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1"),
	)
}
