// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	groupMembersFieldNames          = builder.RawFieldNames(&GroupMembers{})
	groupMembersRows                = strings.Join(groupMembersFieldNames, ",")
	groupMembersRowsExpectAutoSet   = strings.Join(stringx.Remove(groupMembersFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	groupMembersRowsWithPlaceHolder = strings.Join(stringx.Remove(groupMembersFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	groupMembersModel interface {
		Insert(ctx context.Context, data *GroupMembers) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*GroupMembers, error)
		FindOneByGroupIdUid(ctx context.Context, groupId int64, uid int64) (*GroupMembers, error)
		Update(ctx context.Context, data *GroupMembers) error
		Delete(ctx context.Context, id int64) error
	}

	defaultGroupMembersModel struct {
		conn  sqlx.SqlConn
		table string
	}

	GroupMembers struct {
		Id        int64 `db:"id"`
		GroupId   int64 `db:"group_id"`  // 群组ID
		Uid       int64 `db:"uid"`       // 成员UID
		Role      int64 `db:"role"`      // 1群主 2管理员 3普通成员
		Muted     int64 `db:"muted"`     // 是否被禁言 0否 1是
		JoinedAt  int64 `db:"joined_at"` // 加入时间
		CreatedAt int64 `db:"created_at"`
	}
)

func newGroupMembersModel(conn sqlx.SqlConn) *defaultGroupMembersModel {
	return &defaultGroupMembersModel{
		conn:  conn,
		table: "`group_members`",
	}
}

func (m *defaultGroupMembersModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultGroupMembersModel) FindOne(ctx context.Context, id int64) (*GroupMembers, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", groupMembersRows, m.table)
	var resp GroupMembers
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultGroupMembersModel) FindOneByGroupIdUid(ctx context.Context, groupId int64, uid int64) (*GroupMembers, error) {
	var resp GroupMembers
	query := fmt.Sprintf("select %s from %s where `group_id` = ? and `uid` = ? limit 1", groupMembersRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, groupId, uid)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultGroupMembersModel) Insert(ctx context.Context, data *GroupMembers) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?)", m.table, groupMembersRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.GroupId, data.Uid, data.Role, data.Muted, data.JoinedAt)
	return ret, err
}

func (m *defaultGroupMembersModel) Update(ctx context.Context, newData *GroupMembers) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, groupMembersRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.GroupId, newData.Uid, newData.Role, newData.Muted, newData.JoinedAt, newData.Id)
	return err
}

func (m *defaultGroupMembersModel) tableName() string {
	return m.table
}
