// Code generated by MockGen. DO NOT EDIT.
// Source: internal/user/model/users_model.go
//
// Generated by this command:
//
//	mockgen -source=internal/user/model/users_model.go -destination=internal/user/model/users_model_mock.go -package=model -mock_names=UsersModel=MockUsersModel
//

// Package model is a generated GoMock package.
package model

import (
	context "context"
	sql "database/sql"
	reflect "reflect"

	sqlx "github.com/zeromicro/go-zero/core/stores/sqlx"
	gomock "go.uber.org/mock/gomock"
)

// MockUsersModel is a mock of UsersModel interface.
type MockUsersModel struct {
	ctrl     *gomock.Controller
	recorder *MockUsersModelMockRecorder
	isgomock struct{}
}

// MockUsersModelMockRecorder is the mock recorder for MockUsersModel.
type MockUsersModelMockRecorder struct {
	mock *MockUsersModel
}

// NewMockUsersModel creates a new mock instance.
func NewMockUsersModel(ctrl *gomock.Controller) *MockUsersModel {
	mock := &MockUsersModel{ctrl: ctrl}
	mock.recorder = &MockUsersModelMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUsersModel) EXPECT() *MockUsersModelMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockUsersModel) Delete(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockUsersModelMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockUsersModel)(nil).Delete), ctx, id)
}

// FindOne mocks base method.
func (m *MockUsersModel) FindOne(ctx context.Context, id int64) (*Users, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindOne", ctx, id)
	ret0, _ := ret[0].(*Users)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindOne indicates an expected call of FindOne.
func (mr *MockUsersModelMockRecorder) FindOne(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindOne", reflect.TypeOf((*MockUsersModel)(nil).FindOne), ctx, id)
}

// FindOneByUsername mocks base method.
func (m *MockUsersModel) FindOneByUsername(ctx context.Context, username string) (*Users, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindOneByUsername", ctx, username)
	ret0, _ := ret[0].(*Users)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindOneByUsername indicates an expected call of FindOneByUsername.
func (mr *MockUsersModelMockRecorder) FindOneByUsername(ctx, username any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindOneByUsername", reflect.TypeOf((*MockUsersModel)(nil).FindOneByUsername), ctx, username)
}

// Insert mocks base method.
func (m *MockUsersModel) Insert(ctx context.Context, data *Users) (sql.Result, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Insert", ctx, data)
	ret0, _ := ret[0].(sql.Result)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Insert indicates an expected call of Insert.
func (mr *MockUsersModelMockRecorder) Insert(ctx, data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Insert", reflect.TypeOf((*MockUsersModel)(nil).Insert), ctx, data)
}

// Update mocks base method.
func (m *MockUsersModel) Update(ctx context.Context, data *Users) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, data)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockUsersModelMockRecorder) Update(ctx, data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockUsersModel)(nil).Update), ctx, data)
}

// withSession mocks base method.
func (m *MockUsersModel) withSession(session sqlx.Session) UsersModel {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "withSession", session)
	ret0, _ := ret[0].(UsersModel)
	return ret0
}

// withSession indicates an expected call of withSession.
func (mr *MockUsersModelMockRecorder) withSession(session any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "withSession", reflect.TypeOf((*MockUsersModel)(nil).withSession), session)
}
