// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package types

type LoginRequest struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type LoginResponse struct {
	UserId int64  `json:"user_id"`
	Token  string `json:"token"`
}

type PingRequest struct {
}

type PingResponse struct {
	Message string `json:"message"`
}

type RegisterRequest struct {
	Username string `json:"username"`          // 必填
	Password string `json:"password"`          // 必填
	Nickname string `json:"nickname,optional"` // 可选
}

type RegisterResponse struct {
	UserId int64  `json:"user_id"`
	Token  string `json:"token"`
}
