// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package types

type CreateGroupReq struct {
	Name        string  `json:"name"        validate:"required,min=2,max=64"`
	Avatar      string  `json:"avatar"      validate:"omitempty,url"`
	Description string  `json:"description" validate:"omitempty,max=256"`
	MemberUIDs  []int64 `json:"member_uids" validate:"omitempty,max=99"`
}

type CreateGroupResp struct {
	GroupID     int64  `json:"group_id"`
	Name        string `json:"name"`
	MemberCount int    `json:"member_count"`
}

type GetGroupMembersResp struct {
	GroupID     int64         `json:"group_id"`
	Name        string        `json:"name"`
	MemberCount int           `json:"member_count"`
	Members     []GroupMember `json:"members"`
}

type GetMyGroupsResp struct {
	Groups []GroupInfo `json:"groups"`
}

type GroupInfo struct {
	GroupID     int64  `json:"group_id"`
	Name        string `json:"name"`
	Avatar      string `json:"avatar"`
	Description string `json:"description"`
	OwnerUID    int64  `json:"owner_uid"`
	MemberCount int    `json:"member_count"`
}

type GroupMember struct {
	UID      int64  `json:"uid"`
	Nickname string `json:"nickname"`
	Avatar   string `json:"avatar"`
	Role     int    `json:"role"`
	JoinedAt int64  `json:"joined_at"`
}

type JoinGroupReq struct {
	GroupID int64 `json:"group_id" validate:"required"`
}

type KickMemberReq struct {
	GroupID   int64 `json:"group_id"   validate:"required"`
	TargetUID int64 `json:"target_uid" validate:"required"`
}

type QuitGroupReq struct {
	GroupID int64 `json:"group_id" validate:"required"`
}
